CLASS zcl_zsf_com99_01_sql DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

    INTERFACES if_amdp_marker_hdb  .

    CLASS-METHODS ALPHA_in for SCALAR FUNCTION ZSF_COM99_01.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_ZSF_COM99_01_SQL IMPLEMENTATION.


  METHOD alpha_in BY DATABASE FUNCTION FOR HDB LANGUAGE SQLSCRIPT OPTIONS READ-ONLY.
    DECLARE out1 NVARCHAR( 10 );

    out1 :=  ABAP_ALPHANUM( if_input, 10 );

    result = :out1;
  ENDMETHOD.
ENDCLASS.
